// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Examples.GrpcConfiguration.Models {
  public static partial class ExampleService
  {
    static readonly string __ServiceName = "ExampleService";

    static readonly grpc::Marshaller<global::Examples.GrpcConfiguration.Models.MemberCondition> __Marshaller_MemberCondition = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Examples.GrpcConfiguration.Models.MemberCondition.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Examples.GrpcConfiguration.Models.Member> __Marshaller_Member = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Examples.GrpcConfiguration.Models.Member.Parser.ParseFrom);

    static readonly grpc::Method<global::Examples.GrpcConfiguration.Models.MemberCondition, global::Examples.GrpcConfiguration.Models.Member> __Method_GetMember = new grpc::Method<global::Examples.GrpcConfiguration.Models.MemberCondition, global::Examples.GrpcConfiguration.Models.Member>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMember",
        __Marshaller_MemberCondition,
        __Marshaller_Member);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Examples.GrpcConfiguration.Models.ExampleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ExampleService</summary>
    public abstract partial class ExampleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Examples.GrpcConfiguration.Models.Member> GetMember(global::Examples.GrpcConfiguration.Models.MemberCondition request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ExampleService</summary>
    public partial class ExampleServiceClient : grpc::ClientBase<ExampleServiceClient>
    {
      /// <summary>Creates a new client for ExampleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ExampleServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ExampleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ExampleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ExampleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ExampleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Examples.GrpcConfiguration.Models.Member GetMember(global::Examples.GrpcConfiguration.Models.MemberCondition request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMember(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Examples.GrpcConfiguration.Models.Member GetMember(global::Examples.GrpcConfiguration.Models.MemberCondition request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMember, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Examples.GrpcConfiguration.Models.Member> GetMemberAsync(global::Examples.GrpcConfiguration.Models.MemberCondition request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetMemberAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Examples.GrpcConfiguration.Models.Member> GetMemberAsync(global::Examples.GrpcConfiguration.Models.MemberCondition request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMember, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ExampleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ExampleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ExampleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetMember, serviceImpl.GetMember).Build();
    }

  }
}
#endregion
